server:
  port: 7777

spring:
  application:
    name: cshop-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    inetutils:
      ignoredInterfaces:  #禁用网卡
        - docker0
        - veth*
        - en0
        - br*
eureka:
  client:
    service-url:
      defaultZone: http://192.168.56.100:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true #当你获取host时，返回的不是主机名，而是ip
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    cshop-item-service: /cshop/** # 将商品微服务映射到/cshop/**
    cshop-user-service: /user/**
    cshop-auth-service: /auth/**
    cshop-order-service: /order/**
    cshop-cart-service: /cart/**
  #  ignored-services:
  #    - cshop-upload-service # 忽略upload-service服务
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效

ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5 #一个rolling window内最小的熔断请求数，默认超过20自动熔断
        sleepWindowInMilliseconds: 10000 #触发短路的时间值，默认超过5000毫秒后会关闭circuit。
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 命令执行超时时 间，默认1000ms

cshop:
  worker:
    workerId: 1
    dataCenterId: 1
  jwt:
    cookieName: CS_TOKEN
    publicKeyPath: /Users/june/share/rsa.pub # 公钥地址

  filter:
    allowPaths:
      /api/auth
      /api/search
      /api/user/account
      /api/cshop
      /api/order
